FlashyPep/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(30), unique=True, nullable = False)
    password = db.Column(db.String(300), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    score = db.Column(db.Integer, default = 0)
    udeck = db.relationship('Deck', cascade='all, delete-orphan', backref='deck')

class Deck(db.Model):
    __tablename__ = 'deck'
    id = db.Column(db.Integer, primary_key=True)
    deck_name = db.Column(db.String(30))
    user = db.Column(db.String, db.ForeignKey('user.username'), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    score = db.Column(db.Integer, default=0)
    is_public = db.Column(db.Boolean, default = False)
    last_rev = db.Column(db.DateTime(timezone=True), default=func.now())
    dcard = db.relationship('Card', cascade='all, delete-orphan', backref='card')

class Card(db.Model):
    __tablename__ = 'card'
    card_id = db.Column(db.Integer, primary_key=True)
    front = db.Column(db.String(512), nullable = False)
    back = db.Column(db.String(512), nullable = False)
    score = db.Column(db.Integer, default = 0)
    deck = db.Column(db.String, db.ForeignKey('deck.deck_name'), nullable = False)

FlashyPep/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, login_manager
from flask_restful import Api


db = SQLAlchemy()
DB_NAME = "project.sqlite3"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'abulaman'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    api = Api(app)


    from .api import UserAPI, DeckAPI, CardAPI
    
    api.add_resource(UserAPI, '/api/user', '/api/user/<string:username>')
    api.add_resource(DeckAPI, '/api/deck/<string:username>')
    api.add_resource(CardAPI, '/api/<string:username>/<string:deck>/card', '/api/card/<string:card_id>','/api/<string:deck>')

    from .views import views

    app.register_blueprint(views, url_prefix="/")

    from .models import User, Deck, Card

    create_db(app)

    login_manager = LoginManager()
    login_manager.login_view = "views.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return  app, api

def create_db(app):
    if not path.exists("FlashyPep/"+ DB_NAME):
        db.create_all(app=app)
    print('DATABASE ALREADY EXISTS')

FlashyPep/views.py
from re import S
from flask import Blueprint, render_template, request, flash
from flask_login import login_user, logout_user, current_user
from flask_login.utils import login_required
from werkzeug.utils import redirect
from .models import User, Deck, Card
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
import requests
from datetime import datetime

views = Blueprint("views", __name__)

BASE = 'http://0.0.0.0:5432'

@views.route('/dashboard', methods = ['GET', 'POST'])
@login_required
def home():
    data = requests.get(BASE+f'/api/deck/{current_user.username}')
    
    return render_template('dashboard.html', decks=data.json(), user=current_user.username)

@views.route('/', methods=['GET'])
def landing():
    return render_template('landing.html')


@views.route('/review/<string:deck>', methods = ['GET', 'POST'])
@login_required
def review(deck):
    t = datetime.now()
    d=Deck.query.filter_by(deck_name=deck).first()
    d.last_rev=t
    db.session.commit()
    data=requests.get(BASE+ f'/api/{current_user.username}/{deck}/card')
    if data:
        return render_template('review.html', front = data.json()['front'], back = data.json()['back'], deck=data.json()['deck'], card_id=data.json()['card_id'])
    else:
        return render_template('review.html', deck=deck, data=True)


@views.route('/review/<string:deck>/<int:card_id>', methods = ['GET', 'POST'])
def score(deck,card_id):
    if request.method == 'POST':
        c = Card.query.filter_by(card_id=card_id).first()
        s = int(request.form.get('score'))
        c.score = s
        db.session.commit()
        d= Deck.query.filter_by(deck_name=deck, user=current_user.username).first()
        cn = Card.query.filter_by(deck=deck).count()
        d.score = d.score + (c.score/cn)
        db.session.commit()
        return redirect(f'/review/{deck}')


@views.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect('/dashboard')
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Username does not exist.', category='error')

    return render_template('login.html')


@views.route('/register', methods = ['GET', 'POST'])
def register():
    return render_template('register.html')


@views.route('/<string:user>/deck/<string:deck>/delete', methods=['GET','POST'])
def deletedeck(deck, user):
    d= Deck.query.filter_by(deck_name=deck, user=user).first()
    db.session.delete(d)
    db.session.commit()
    return redirect('/dashboard')


@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/')

FlashyPep/templates/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <style>
            body{
              background-image: url("{{ url_for('static', filename='img/back.jpg') }}");
              background-size: 100% 400%;
              
              background-repeat: no-repeat;
            }
         </style>
    </head>

    <body>
      <h4></h4>
        <header class="p-3 bg-primary text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FlashyPep</a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="d-flex align-items-right mb-2 mb-lg-0 text-white text-decoration-none"> &nbsp Home</a></li>
                </ul>

                <div class="text-end">
                <a href="{{ url_for('views.logout') }}" class="btn btn-danger">Logout</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>

        <div class="container mt-5 mb-5">
            <div class="row mt-1">
                {% for d in decks %}
                <div class="col-md-4">
                    <div class= "container">
                        <div class="card">
                            <div class="front">{{ d['deck_name'] }}</div>
                            <div class="back">
                                <ul>
                                    <li> score: {{ d['score'] }} </li>
                                    <li> last rev. time:{{ d['last_rev'] }} </li>
                                </ul>
                                <div class="btn-group" role="group">
                                    <a href="/review/{{ d['deck_name'] }}" class="btn btn-outline-dark">Add Cards/Review</a>
                                    <a href="/{{ user }}/deck/{{ d['deck_name'] }}/delete" class="btn btn-outline-dark">Delete Deck</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="col-md-4">
                    <!-- Button trigger modal -->
                    
                    <button type="button" class="btn btn-success add" data-toggle="modal" data-target="#exampleModal">
                        Add Deck
                    </button>
                    
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form class="row g-3" action="/api/deck/{{ user }}" method="POST">
                              <div class="col-auto">
                                <label for="deckname" class="visually-hidden">Deck Name</label>
                                <input type="text" class="form-control" id="inputPassword2" placeholder="Deck Name" name="deck_name">
                              </div>
                              <div class="col-auto">
                                <button type="submit" class="btn btn-primary mb-3">Add</button>
                              </div>
                            </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

FlashyPep/templates/landing.html
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style type="text/css">
            header.masthead {
                  padding-top: 20rem;
                    }
            body{
              background-image: url("{{ url_for('static', filename='img/orchid.jpg') }}");
              background-size: 100% 125%;
            }
        </style>
    </head>
    
    <body id="page-top">
      <header class="p-3 bg-primary text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FlashyPep</a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="d-flex align-items-right mb-2 mb-lg-0 text-white text-decoration-none"> &nbsp Home</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
                </form>

                <div class="text-end">
                <a href="{{ url_for('views.login') }}" class="btn btn-danger">Login</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>

        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-black font-weight-bold">Ever heard of FlashyPep?</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <h5 class="text-black">FlashyPep is your ONE STOP destination for flashcards</h5>
                        <h5 class="text-black">Using FlashyPep, you can create your own Flashcard decks, and check out other pre-existing decks to play and learn from</h5><br>
                        <a class="btn btn-primary btn-xl" href="{{ url_for('views.register') }}">Get Started</a>
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

FlashyPep/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            body{
              background-image: url("{{ url_for('static', filename='img/pencil.jpg') }}");
              background-size: 100% 150%;
            }
         </style>
    </head>
    <body>
    <header class="p-3 bg-primary text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FlashyPep     
                </a>
                <br>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="d-flex align-items-right mb-2 mb-lg-0 text-white text-decoration-none"> &nbsp Home</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
                </form>

                <div class="text-end">
                <a href="{{ url_for('views.login') }}" class="btn btn-danger">Login</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>
         
        <div class="sidenav">
         <div class="login-main-text">
            <h3>FlashyPep - Login Page</h3><br><br>
            <h3>Make FlashyPep your best "back to school" friend, here's how:</h3><br>
            <i><ul>
            <li>Remember physics formulas</li>
            <li>Remember history dates</li>
            <li>Learn math equations</li>
            <li>Enhance your vocabulary for any language</li>
            </ul></i>
         </div>
      </div>
      <div class = "container" align = "center">
      <div class="main">
         <div class="col-md-6 col-sm-12">
         {% with messages = get_flashed_messages(with_categories=True) %}
         {% if messages %}
         {% for category, message in messages %}
            <div class = "alert alert-danger alert-dismissable fade show" role = "alert">
            {{ message }} 
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
         {% endfor %}
         {% endif %}
         {% endwith %}
            <div class="login-form">
               <form action = "{{ url_for('views.login') }}" method = "POST">
                  <div class="form-group">
                     
                     <input type="text" class="form-control" placeholder="User Name" name="username">
                  </div>
                  <div class="form-group">
                     <br>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  <br>
                  <small><i>Not a user yet?, <a href="{{ url_for('views.register') }}">Register now...</a></i></small>
                  <button style="width:100px;margin: 15px;" type="submit" class="btn btn-dark">Login</button>
               </form>
            </div>
         </div>
      </div>
      </div>
    
        
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

FlashyPep/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            body{
              background-image: url("{{ url_for('static', filename='img/poarch.jpg') }}");
              background-size: 100% 140%;
            }
         </style>
    </head>
    <body> 
      <header class="p-3 bg-primary text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FlashyPep</a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="d-flex align-items-right mb-2 mb-lg-0 text-white text-decoration-none"> &nbsp Home</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
                </form>

                <div class="text-end">
                <a href="{{ url_for('views.login') }}" class="btn btn-danger">Login</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>
   
      <div class="sidenav">
         <div class="login-main-text">
            <h3>FlashyPep - Register Page</h3><br>
            <h3>Remember the things that matter to you the most</h3><br>
            <h3> Fun ways to use FlashyPep:</h3><br>
            <i><ul>
            <li>Memorize recipies</li>
            <li>Remember birthdays</li>
            <li>Remember names of extended family members</li>
            <li>Memorize phone numbers</li>
            </ul></i>
         </div>
      </div>
      
      <div class = "container" align = "center">
      <div class="main">
         <div class="col-md-6 col-sm-12">
         <div class="container">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
               <div class = "alert alert-danger alert-dismissable fade show" role = "alert">
               {{ message }} 
               <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
               </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
         </div>
            <div class="login-form">
               <form action ="/api/user" method = "POST">
                  <div class="form-group">
                     
                     <input type="text" class="form-control" placeholder="User Name" name="username">
                  </div>
                  <div class="form-group">
                     <br>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  <br>
                  <small><i>Have an account already?, <a href="{{ url_for('views.login') }}">Login now...</a></i></small>
                  
                  <button style="width:100px;margin: 15px;" type="submit" class="btn btn-dark">Register</button>
               </form>
            </div>
         </div>
      </div>
      </div>
      
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

FlashyPep/templates/review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <style>
            body{
              background-image: url("{{ url_for('static', filename='img/calender.jpg') }}");
              background-size: 100% 150%;
              background-repeat: no-repeat;
            }

            .maincontainer{
              position:relative;
              width: 250px;
              height: 320px;
            }

            .thecard{
              position:absolute;
              width: 100%;
              height: 100%;
              transform-style: preserve-3d;
              transition: all 0.5s ease;
            }

            .thecard:hover{
              transform:rotateY(180deg);
            }

            .thefront{
              position:absolute;
              width: 100%;
              height: 100%;
              backface-visibility: hidden;
              background: yellow;
              color: black;
              text-align: center;
              border-radius: 20px;
              font-size: 40px;
              font-weight: bold;
              padding-top: 115px;
            }

            .theback{
              position:absolute;
              width: 100%;
              height: 100%;
              backface-visibility: hidden;
              background: yellow;
              color:black;
              transform:rotateY(180deg);
              text-align: center;
              border-radius: 20px;
              font-size: 40px;
              font-weight: bold;
              padding-top: 115px;
            }
        </style>
    
    </head>
    <body>
              <header class="p-3 bg-primary text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FlashyPep</a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/dashboard" class="d-flex align-items-right mb-2 mb-lg-0 text-white text-decoration-none"> &nbsp Dashboard</a></li>
                </ul>
                
                <div class="text-end">
                <a href="{{ url_for('views.logout') }}" class="btn btn-danger">Logout</a>
                
                </div>
            </div>
            </div>
        </header>

<br><br>
    <center>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal"> + Add Cards</button><br><br>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form class="row g-3" action="/api/{{ deck }}" method="POST">
                  <div class="col-auto">
                    <label for="front" class="visually-hidden">Front</label>
                    <input type="text" class="form-control" id="front" placeholder="front..." name="front">
                    <br>
                    <label for="back" class="visually-hidden">Back</label>
                    <input type="text" class="form-control" id="back" placeholder="back..." name="back">
                  </div>
                  <div class="col-auto"><br><br>
                    <button type="submit" class="btn btn-primary mb-3">Add</button>
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </center>

        <center>
            <div class="big">
            
            <div class = "maincontainer">
                  <div class = "thecard">
                    <div class = "thefront">{% if data %} No Cards Yet {% else %} {{front}} {% endif %}</div>
                    <div class = "theback">{% if data %} Click Add Cards to get started {% else %} {{back}} {% endif %}</div>
                    </div>
                  </div>
            </div>
            <br><br>
            <form id="autoform" action="/review/{{ deck }}/{{ card_id }}" method="POST" name="autoform">    
                <div class="rating">
                    <h4>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata5" value="5" {% if data %} disabled {% endif %}><label for="rata5"><b>SuperEasy</b></label>&nbsp &nbsp
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata4" value="4" {% if data %} disabled {% endif %}><label for="rata4"><b>Easy</b></label>&nbsp &nbsp
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata3" value="3" {% if data %} disabled {% endif %}><label for="rata3"><b>Normal</b></label>&nbsp &nbsp
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata2" value="2" {% if data %} disabled {% endif %}><label for="rata2"><b>Hard</b></label>&nbsp &nbsp
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata1" value="1" {% if data %} disabled {% endif %}><label for="rata1"><b>RocketScience</b></label>
                    </h4>
                </div>
            </form>
            </div>   
        </center>
    </body>
</html>